# Generated by Django 4.0.6 on 2022-08-03 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('student_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('PROF.DR', 'prof.dr'), ('DOC', 'Doc'), ('DR', 'Dr')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('exam_timeslot', models.IntegerField()),
                ('room', models.CharField(max_length=10)),
                ('req_inv', models.PositiveSmallIntegerField()),
                ('exam_weight', models.FloatField()),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.lecturer'),
        ),
    ]
